<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>xbrlplus</ToolCommandName>
    <!-- dotnet xbrlplus で呼び出す -->
    <PackageId>xbrlplus</PackageId>
    <Version>0.0.7</Version>
    <Authors>manpukupanda</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>xbrl;EDINET</PackageTags>

  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Manpuku.Edinet.Manifest" Version="0.0.3" />
    <PackageReference Include="Manpuku.Edinet.Xbrl" Version="0.0.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <Target Name="CopyReadme" BeforeTargets="PrepareForBuild">
    <Copy SourceFiles="../README.md" DestinationFolder="$(ProjectDir)" />
  </Target>
  
</Project>
